### ISSUE TITLE
Purge old nightlies from the S3 bucket

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats-packer#18]
On each commit to master and every night, a new set of build artifacts is published to the beats-nightlies S3 bucket. Should these artifacts be treated as transient and be purged after a period of time?

If so, we can configure S3 to manage the lifecycle of the artifacts for us. See https://docs.aws.amazon.com/AmazonS3/latest/UG/lifecycle-configuration-bucket-no-versioning.html

**Comment by ruflin** [comment]
@andrewkroh Good point. I suggest to keep nightlies for a maximum of 60 days (or even less).

**Comment by andrewkroh** [comment]
The lifecycle is set to 14 days. It can easily be changed through the S3 Management Console.

![screen shot 2015-11-13 at 9 16 22 am](https://cloud.githubusercontent.com/assets/4565752/11147892/46e559cc-89e7-11e5-84e9-7dcebba9321d.png)

**Comment by ruflin** [comment]
:+1:
