### ISSUE TITLE
A statically linked filebeat binary

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats-packer#23]
beats-packer produces a dynamically linked Filebeat binary when a statically linked binary would be preferred for portability.

See https://discuss.elastic.co/t/static-build/34354

**Comment by bobelev** [comment]
any updates on that?

**Comment by batmat** [comment]
+1. IMO the fact that filebeat isn't statically linked somehow goes against its goal: being lightweight and easily deployable.

Having a static binary really makes the deployment process a no-brainer: copy the binary where it's due and be done (or baking it in a Docker image).

(No offense, just voicing a concern. Thanks for the great products :-)).

**Comment by andrewkroh** [comment]
Filebeat is statically linked now (and has been for a bit).

And docker images are being worked at https://github.com/elastic/beats-docker

**Comment by alainvanhoof** [comment]
Filebeat is indeed completely static, but what about metric/packet beat?
