### ISSUE TITLE
Add systemd support

### ISSUE THREAD

**Issue by andrewkroh** [elastic/beats-packer#39]
Currently the packages provide SysV-style init scripts, but a lot of operating system primarily use systemd so we should provide packages that contain systemd scripts for those OS'es.

/cc: @dakrone

**Comment by dakrone** [comment]
+1, would love to have systemd scripts.

**Comment by jordansissel** [comment]
@andrewkroh [pleaserun](http://github.com/jordansissel/pleaserun) could offer you a quick starting point for a systemd service definition, if you want some automation :)

**Comment by sijis** [comment]
This seems related to issue #35 too.

**Comment by urso** [comment]
Also related (CentOS 7): elastic/filebeat#309

service file by @sijis also works with Centos 7 AMI.

**Comment by tsg** [comment]
This was done by #44.
