### ISSUE TITLE
Unable to install nightly build on Debian: 'Version' field string 'nightly151208141331': version number does not start with digit

### ISSUE THREAD

**Issue by marnovdm** [elastic/beats-packer#40]
As requested by @ruflin after first reporting in beats repo: https://github.com/elastic/beats/issues/481

dpkg -i filebeat_nightly.latest_amd64.deb 
dpkg: error processing archive filebeat_nightly.latest_amd64.deb (--install):
parsing file '/var/lib/dpkg/tmp.ci/control' near line 2 package 'filebeat':
error in 'Version' field string 'nightly151208141331': version number does not start with digit
Errors were encountered while processing:
filebeat_nightly.latest_amd64.deb

Trying to install on Debian 8 64 bit VM. The stable release can be installed, but I would like to test some of the resolved issues in the latest nightly build. Got the filebeat nightlies from here: https://beats-nightlies.s3.amazonaws.com/index.html?prefix=filebeat/

**Comment by tsg** [comment]
This is fixed by #44.
