### ISSUE TITLE
Build failure on master

### ISSUE THREAD

**Issue by raboof** [elastic/beats-packer#59]
Master currently fails because it tries to apply `gopacket_pcap.patch` to the beats framework, but this patch needs an update to apply cleanly

**Comment by ruflin** [comment]
Beats packer was moved to the beats repository to make the building easier and also make it available for community beats. It can be found under `dev-tools`: https://github.com/elastic/beats/tree/master/dev-tools This repository is still around as we need it for the 1.x builds which do not contain the `dev-tools` folder yet. 

If you are building your own beat, I recommend to update to the most recent libbeat version and use `make package` command.

**Comment by raboof** [comment]
Indeed! Thanks for the follow-up :)
